name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Descarga el código del repo
      - uses: actions/checkout@v3

      # Instala Java 17 (puedes cambiar si usas otra versión)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Construye el proyecto con Maven
      - name: Build with Maven
        run: mvn -B clean verify
